### ISSUE TITLE
How does IRC reporting work on this software?

### ISSUE THREAD

**Issue by FrosticleFall** [Kak2X/jul#1]
Hi,

I can't search the repo (because it's a fork), how exactly does the IRC reporting function work? I want to use it on my VPS, for my board.

Would I need some kind of bot in the channel etc. or something else? Note that I would have asked you in the IRC on Jul or something but I've got to go in 10 minutes, so yeah I can't, and I can't double post on Kafuka ;P

Hope to hear from you!
~Jamie

**Comment by Kak2X** [comment]
the "prepare to irc" function is pretty much the same as how it was in the original code:
https://github.com/Kak2X/jul/blob/master/lib/function.php#L2144
**xk_ircsend**("[id]|[message]");
where 'id' is the numeric channel ID (you can use here constant aliases such as IRC_MAIN or IRC_STAFF)


as for actually sending messages to IRC... the code isn't there. In the original board, it sends data to another service with code not provided. said service is also specific to jul, so it can't be reused

though you definitely need a bot which connects to IRC and listens to something (ie: another port) for messages
